### ISSUE TITLE
teensy++ 2.0

### ISSUE THREAD

**Issue by dynamicalsystem** [robnormal/teensy-chorded-keyboard#1]
Hi there,

I've forked your work and tried to get it working.  Would you be so kind as to give me a little help?

I'm not doing anything fancy - just compiling the three source files in the Arduino IDE with Teensyduino then downloading to a teensy++ 2.0.

The teensy has pushbuttons connected to pins 0-9.  Pin 6 on this version is a LED pin which I've overridden with a 1KΩ pullup resister.  I've tested it with a [sketch](https://github.com/DynamicalSystem/teensyBrailler) that proves each button connects and breaks.

When I burn teensy-chorded-keyboard to it I get no behaviour.  It all compiles and uploads but the buttons don't do anything.  I stuck some keyboard.println() lines in various points and I can see the loop works.

Any ideas?

DS

**Comment by robnormal** [comment]
When you say the loop works, is it calling sendOutputIO() with the expected output? If so, is sendKeyIO() making the proper calls to the Keyboard methods?

**Comment by dynamicalsystem** [comment]
OK - I had it upside down - your code assumes 5v when a key is pushed - I had assumed pullup - 0v when pushed.

Thanks for getting back to me so quickly.

DS
